# This file contains the Persistent Volume (PV) and Persistent Volume Claim (PVC) configurations for a PostgreSQL database in a Kubernetes cluster.
# Persistent Volume and Persistent Volume Claim for PostgreSQL Database

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: webapp-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: webapp-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
