# ConfigMap for web application configuration
# This file defines a ConfigMap resource for a web application.
# It contains environment variables and configuration settings for the application.

apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp-demo
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "webapp_user"
