apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp-demo
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "webapp_user"
