apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp-demo
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        - name: copy-app-code
          image: busybox
          command: ["sh", "-c", "cp -r /source/* /app/"]
          volumeMounts:
            - name: app-code-config
              mountPath: /source
            - name: app-code
              mountPath: /app
      containers:
        - name: webapp
          image: bitnami/php-fpm:8.2
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: webapp-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: app-code
              mountPath: /app
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: app-code-config
          configMap:
            name: app-code
