apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: webapp-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role
  namespace: webapp-demo
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding
  namespace: webapp-demo
subjects:
  - kind: ServiceAccount
    name: webapp-sa
    namespace: webapp-demo
roleRef:
  kind: Role
  name: webapp-role
  apiGroup: rbac.authorization.k8s.io
